### ISSUE TITLE
Multiple Feature requests

### ISSUE THREAD

**Issue by vipulgupta2048** [Rohithgilla12/PyCon-Twitter-Bot#11]
After merging #9 and closing #10, these features need to be implemented before adding repository to pythonindia org.

- The bot retweets its own tweets if someone retweets them. Case in reference.

![](https://cdn.discordapp.com/attachments/428399832743280640/454564294537773056/Screenshot_2018-06-08-14-04-16-916_com.twitter.android.png) 

Possible Solution suggested by @inovizz  - Maintain an array original tweet ids, to avoid duplication clean it up after every couple of days in case of retweets.

- Bot needs to like tweets as well. 
- The retweet part of the code doesn't look good to me, can me do retweet with comment as referenced here - https://stackoverflow.com/a/33620770/1356851 (In comment we need to mention #PyConIndia2018 and #PyConIndia no need to add RT and twitter handle again for now)

**Comment by vipulgupta2048** [comment]
I like to work on this issue, to learn more on the API and be proficient at it.

**Comment by Rohithgilla12** [comment]
Ok @vipulgupta2048  work on it.
And this multiple error came because of me. I was unknowingly running the code thrice at same time.
Sorry will make sure it doesn't happen again.
