### ISSUE TITLE
Make the code generic - branch Volunteer file: volunteer.py

### ISSUE THREAD

**Issue by a2un** [Rohithgilla12/PyCon-Twitter-Bot#13]
In this function in Volunteer.Py Count==2 is hard coded (to mean the number of search terms in the config py must match with those in the tweet). Remove this and all values hard codes and pull values from config.py only and change it to len of the search terms array

def checkSearchTerms(searchterms,tags):
   ......
   ......
    return (count == 2)  #change this to length of tagschecklist, picked from config.py

**Comment by vipulgupta2048** [comment]
Hi, @a2un The issue seems very poorly made with no conclusive points. Please state what you are referring to and which branch of the project, what needs to be fixed.

**Comment by a2un** [comment]
Hi, @vipulgupta2048 the issue isn't for public. Thanks for looking at it but I am just keeping a reminder for me to make some changes.

**Comment by a2un** [comment]
Updates comments and description hope it seems more conclusive now

**Comment by a2un** [comment]
Updated the title and comments hope it is more conclusive now

**Comment by Rohithgilla12** [comment]
Hey, since this is a short script , why are you making it complicated by adding another file with bunch of functions and then using them in main.py. @a2un

**Comment by a2un** [comment]
You're welcome to make changes that seem better to be made on this.
